#!/bin/sh
# Install a LaunchAgent whose *script* lives outside Dropbox.
# macOS TCC blocks launchd from executing files under Library/CloudStorage.
set -e
ROOT="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
LABEL="com.ajoros.ai-weather-guy.update"
SUPPORT="$HOME/Library/Application Support/ai-weather-guy"
RUNNER="$SUPPORT/run.sh"
DEST="$HOME/Library/LaunchAgents/${LABEL}.plist"

mkdir -p "$SUPPORT" "$HOME/Library/LaunchAgents" "$ROOT/.cache"
cat > "$RUNNER" <<EOF
#!/bin/sh
# Generated by install_update_agent.sh — do not edit.
export GOOGLE_CLOUD_PROJECT="weathernext3-joros"
export PATH="/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$PATH"
cd "$ROOT" || exit 1
exec "$ROOT/update_local.sh"
EOF
chmod +x "$RUNNER"

cat > "$DEST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${RUNNER}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${SUPPORT}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>GOOGLE_CLOUD_PROJECT</key>
    <string>weathernext3-joros</string>
  </dict>
  <key>StartInterval</key>
  <integer>1800</integer>
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>${SUPPORT}/agent.log</string>
  <key>StandardErrorPath</key>
  <string>${SUPPORT}/agent.log</string>
</dict>
</plist>
EOF

UID_N="$(id -u)"
launchctl bootout "gui/${UID_N}/${LABEL}" 2>/dev/null || true
launchctl bootstrap "gui/${UID_N}" "$DEST"
echo "installed runner $RUNNER" >&2
echo "Grant Full Disk Access to /bin/sh, then: launchctl kickstart -k gui/${UID_N}/${LABEL}" >&2
